### ISSUE TITLE
PKGBUILD for Arch Linux user repository

### ISSUE THREAD

**Issue by patrickhanft** [thatmattlove/oui#2]
Heyho!

I came across your useful tool a few days ago on Twitter. Thanks for creating that!

I tried to create a PKGBUILD and uploaded it to the Arch Linux User repository. Therefore Arch users should be able to build your tool with their favorite AUR helper tool.

This is the first time for me writing a PKGBUILD file for a go project. And as I'm no developer myself, I guess there could be some things to improve. I'm open to any suggestions.

See https://aur.archlinux.org/packages/oui/

Well, this issue is just to notify you or give feedback. So just close it as you like. :-) 

Best wishes!

**Comment by thatmattlove** [comment]
Very cool! I had originally tried getting Arch packages with golreleaser and uploaded to Fury alongside the Debian/RHEL packages, but they failed for some reason, so I gave up. But, if you're able to maintain this so that it's reasonably up to date, that would be wonderful!
