### ISSUE TITLE
0.0% Downloading vendor data...SQL logic error: near "2.0": syntax error (1)

### ISSUE THREAD

**Issue by warrengottlieb** [thatmattlove/oui#4]
Hiya, I'm seeing the following error whenever I try to lookup or update the db: 

`Updating MAC Address Database
▌░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.0% Downloading vendor data...SQL logic error: near "2.0": syntax error (1)`

I've installed this on a Mac (Sonoma 14.0) and on Ubuntu 22.04 (PopOS) and I'm seeing the same error. 

Thanks!

**Comment by warrengottlieb** [comment]
Thanks for the quick fix, I love this tool!

**Comment by thatmattlove** [comment]
Great to hear, thanks!
